/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MembersRouteImport } from './routes/members'
import { Route as MatrimonyRouteImport } from './routes/matrimony'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatrimonyRegisterRouteImport } from './routes/matrimony.register'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrimonyRoute = MatrimonyRouteImport.update({
  id: '/matrimony',
  path: '/matrimony',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrimonyRegisterRoute = MatrimonyRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => MatrimonyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/matrimony': typeof MatrimonyRouteWithChildren
  '/members': typeof MembersRoute
  '/register': typeof RegisterRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/matrimony/register': typeof MatrimonyRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/matrimony': typeof MatrimonyRouteWithChildren
  '/members': typeof MembersRoute
  '/register': typeof RegisterRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/matrimony/register': typeof MatrimonyRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/matrimony': typeof MatrimonyRouteWithChildren
  '/members': typeof MembersRoute
  '/register': typeof RegisterRoute
  '/scholarships': typeof ScholarshipsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/matrimony/register': typeof MatrimonyRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/events'
    | '/login'
    | '/matrimony'
    | '/members'
    | '/register'
    | '/scholarships'
    | '/sitemap.xml'
    | '/matrimony/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/events'
    | '/login'
    | '/matrimony'
    | '/members'
    | '/register'
    | '/scholarships'
    | '/sitemap.xml'
    | '/matrimony/register'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/events'
    | '/login'
    | '/matrimony'
    | '/members'
    | '/register'
    | '/scholarships'
    | '/sitemap.xml'
    | '/matrimony/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  MatrimonyRoute: typeof MatrimonyRouteWithChildren
  MembersRoute: typeof MembersRoute
  RegisterRoute: typeof RegisterRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrimony': {
      id: '/matrimony'
      path: '/matrimony'
      fullPath: '/matrimony'
      preLoaderRoute: typeof MatrimonyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrimony/register': {
      id: '/matrimony/register'
      path: '/register'
      fullPath: '/matrimony/register'
      preLoaderRoute: typeof MatrimonyRegisterRouteImport
      parentRoute: typeof MatrimonyRoute
    }
  }
}

interface MatrimonyRouteChildren {
  MatrimonyRegisterRoute: typeof MatrimonyRegisterRoute
}

const MatrimonyRouteChildren: MatrimonyRouteChildren = {
  MatrimonyRegisterRoute: MatrimonyRegisterRoute,
}

const MatrimonyRouteWithChildren = MatrimonyRoute._addFileChildren(
  MatrimonyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  MatrimonyRoute: MatrimonyRouteWithChildren,
  MembersRoute: MembersRoute,
  RegisterRoute: RegisterRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
